const Broccolish = {
  name: "Cubic Disarray",
  price: "2e+31",
  priceAsInt: 20,
  start: { txNumber: 5 },
  duration: 100,
  maximum_runs: 20,
  current_run: 0,
  current_sold: 0o0,
  maximum_sold: 10,
  pause_between: 0,
  on_pause: false,
  finished_series: false,
  current_start_tx: null,
  description: "blocks getting more random",
};