


export const africa = {
  "Algeria": "DZA",
  "Angola": "AGO",
  "Benin": "BEN",
  "Botswana": "BWA",
  "Burkina Faso": "BFA",
  "Burundi": "BDI",
  "Cameroon": "CMR",
  "Congo": "COG",
  "Democratic Republic of Congo": "COD",
  "Egypt": "EGY",
  "Gabon": "GAB",
  "Ghana": "GHA",
  "Kenya": "KEN",
  "Lesotho": "LSO",
  "Malawi": "MWI",
  "Mali": "MLI",
  "Mauritania": "MRT",
  "Mauritius": "MUS",
  "Mayotte": "MYT",
  "Morocco": "MAR",
  "Mozambique": "MOZ",
  "Namibia": "NAM",
  "Niger": "NER",
  "Nigeria": "NGA",
  "Reunion": "REU",
  "Rwanda": "RWA",
  "Senegal": "SEN",
  "South Africa": "ZAF",
  "Swaziland": "SWZ",
  "Tanzania": "TZA",
  "Togo": "TGO",
  "Tunisia": "TUN",
  "Uganda": "UGA",
  "Zambia": "ZMB",
  "Zimbabwe": "ZWE",
};
export const americas = {
  "Anguilla": "AIA",
  "Antigua & Barbuda": "ATG",
  "Argentina": "ARG",
  "Aruba": "ABW",
  "Bahamas": "BHS",
  "Barbados": "BRB",
  "Bermuda": "BMU",
  "Bonaire, St Eustatius, Saba": "BES",
  "Brazil": "BRA",
  "Canada": "CAN",
  "Cayman Islands": "CYM",
  "Chile": "CHL",
  "Clipperton Island": "PYF",
  "Colombia": "COL",
  "Curaçao": "CUW",
  "Dominica": "DMA",
  "Falkland Islands (Malvinas)": "FLK",
  "Grenada": "GRD",
  "Guadeloupe": "GLP",
  "Haiti": "HTI",
  "Jamaica": "JAM",
  "Martinique": "MTQ",
  "Mexico": "MEX",
  "Montserrat": "MSR",
  "Peru": "PER",
  "Puerto Rico": "PRI",
  "Saint Barthélemy": "BLM",
  "Saint Kitts & Nevis": "KNA",
  "Saint Lucia": "LCA",
  "Saint Martin (French part)": "MAF",
  "Saint Pierre & Miquelon": "SPM",
  "Saint Vincent & Grenadines": "VCT",
  "Saint Maarten (Dutch part)": "SXM",
  "South Georgia & Sandwich Islands": "SGS",
  "Trinidad & Tobago": "TTO",
  "Turks & Caicos Islands": "TCA",
  "United States": "USA",
  "Uruguay": "URY",
  "Venezuela": "VEN",
  "Virgin Islands (British)": "VGB",
  "Virgin Islands (U.S.)": "VIR",
};
export const asia_pacific = {
  "Australia": "AUS",
  "Brunei": "BRN",
  "Cambodia": "KHM",
  "Guam": "GUM",
  "Hong Kong": "HKG",
  "India": "IND",
  "Indonesia": "IDN",
  "Lao People's Democratic Republic": "LAO",
  "Macao": "MAC",
  "Malaysia": "MYS",
  "Myanmar": "MMR",
  "New Zealand": "NZL",
  "Philippines": "PHL",
  "Singapore": "SGP",
  "South Korea": "KOR",
  "Taiwan": "TWN",
  "Thailand": "THA",
  "Viet Nam": "VNM",
};
export const europe = {
  "Albania": "ALB",
  "Andorra": "AND",
  "Austria": "AUT",
  "Belarus": "BLR",
  "Belgium": "BEL",
  "Bosnia-Herzegovina": "BIH",
  "Bulgaria": "BGR",
  "Croatia": "HRV",
  "Cyprus": "CYP",
  "Czech Republic": "CZE",
  "Denmark": "DNK",
  "Estonia": "EST",
  "Finland": "FIN",
  "France": "FRA",
  "Germany": "DEU",
  "Gibralter": "GIB",
  "Greece": "GRC",
  "Hungary": "HUN",
  "Iceland": "ISL",
  "Ireland (Republic of)": "IRL",
  "Italy": "ITA",
  "Latvia": "LVA",
  "Liechtenstein": "LIE",
  "Lithuania": "LTU",
  "Luxembourg": "LUX",
  "Macedonia": "MKD",
  "Malta": "MLT",
  "Moldova": "MDA",
  "Monaco": "MCO",
  "Montenegro": "MNE",
  "Netherlands": "NDL",
  "Norway": "NOR",
  "Poland": "POL",
  "Portugal": "PRT",
  "Romania": "ROU",
  "Russian Federation": "RUS",
  "San Marino": "SMR",
  "Serbia": "SRB",
  "Slovakia": "SVK",
  "Slovenia": "SVN",
  "Spain": "ESP",
  "Sweden": "SWE",
  "Switzerland": "CHE",
  "Turkey": "TUR",
  "Ukraine": "UKR",
  "United Kingdom": "GBR",
  "Vatican City": "VAT",
};
export const middle_east = {
  "Bahrain": "BHR",
  "Iraq": "IRQ",
  "Jordan": "JOR",
  "Kuwait": "KWT",
  "Lebanon": "LBN",
  "Oman": "OMN",
  "Qatar": "QAT",
  "Saudi Arabia": "SAU",
  "United Arab Emirates": "ARE",
  "Yemen": "YEM",
};
